### ISSUE TITLE
Serverside make express server with user creation

### ISSUE THREAD

**Issue by choucalate** [kkolli/MathGame#11]
Include routes to user creation

**Comment by choucalate** [comment]
also- Enable checking to see if FBID is new user or if it's an old user

**Comment by edchiou** [comment]
I'm not sure what this issue entails. Local user creation when the user signs up via Facebook?

**Comment by choucalate** [comment]
this is a duplicate issue that i just implemented in one issue
https://github.com/kkolli/MathGame/issues/10
