### ISSUE TITLE
Algorithm for generating equations

### ISSUE THREAD

**Issue by edchiou** [kkolli/MathGame#2]
Create an algorithm for generating complete equations that can scale with difficulty.

**Comment by edchiou** [comment]
In order to close this issue, we need further discussion to define bounds for target numbers and the numbers that players will use to reach the targets.

**Comment by tjlevine** [comment]
this looks interesting: http://codetheory.in/weighted-biased-random-number-generation-with-javascript-based-on-probability/

basically gives a couple strategies for how to generate a weighted distribution from a uniform one. Its for js but I think it should be pretty easily adapted for our purposes.

But yeah, we need to pin down what kind of distribution we want. Its probably going to be a lot of trial and error, but just come up with some guess that you think would work and we can refine it later.

**Comment by tjlevine** [comment]
as far as scaling difficulty, lower difficulty should be a more left-skewed distribution, and the distribution should become less and less left-skewed as it gets harder (assuming here that our range is 0-99). Any other ideas for difficulty scaling?

**Comment by edchiou** [comment]
For the meantime, the distribution will be like this:
- 1-10 will each have probability 0.055
- 11-100 will each have probability 0.005

In the near future, I will try to tweak it so there is varying probability in the 11-100 range.
