### ISSUE TITLE
[Low Priority] UIAlertController on network failures

### ISSUE THREAD

**Issue by choucalate** [kkolli/MathGame#34]
https://www.google.com/search?q=uialertcontroller&espv=2&biw=1440&bih=782&source=lnms&tbm=isch&sa=X&ei=vnjvVNbSE5bqoAS-z4DgBg&ved=0CAYQ_AUoAQ&dpr=2#imgdii=_&imgrc=gkXG4_TI9WhEBM%253A%3BH0pPGXgPHog31M%3Bhttp%253A%252F%252Fwww.appcoda.com%252Fwp-content%252Fuploads%252F2014%252F08%252Fuialertcontroller-style.png%3Bhttp%253A%252F%252Fwww.appcoda.com%252Fuialertcontroller-swift-closures-enum%252F%3B600%3B561

make something like this in case network fails and no one knows what happened lol

**Comment by edchiou** [comment]
Closing because this issue is minor and unlikely.
