### ISSUE TITLE
Promotional Video

### ISSUE THREAD

**Issue by edchiou** [kkolli/MathGame#8]
Quoted from Piazza:

> You will submit a promotional video not more than 2 mins in length
> - See  for eg: https://www.youtube.com/watch?v=EZ0uqfDaXeM  & https://www.youtube.com/watch?v=eU3tq9pPvI4  
> - Make the title in Youtube " Your Project Name -  CSE 190 UCSD Mobile Programming Winter 2015 "

**Comment by tjlevine** [comment]
I'm working on this in conjunction with the website, see that issue report for more details
