### ISSUE TITLE
Website documenting evolution of app

### ISSUE THREAD

**Issue by edchiou** [kkolli/MathGame#9]
Quote from Piazza:

> You will create  a website documenting the evolution of your app (use ideas from image below)

![image](https://cloud.githubusercontent.com/assets/1447728/5929034/002f7936-a635-11e4-8ad7-51eaab890195.png)

**Comment by edchiou** [comment]
@kkolli Since you own this repo, can you setup a site at https://pages.github.com/?

**Comment by kkolli** [comment]
@edchiou Done, Here is the link: http://kkolli.github.io/MathGame. You can use the branch gh-pages to edit.

**Comment by tjlevine** [comment]
I got clearance from my CAT 125 TA to use speedy as my media project, so I'm going to take over the website and promotional video. I set registered the speedyapp.github.io site and I pushed a placeholder site there using the github page generator. I'll post more as I continue to develop it.
